import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,chmod} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import http from 'node:http';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {validateScenes,composePrompt} from '../lib/core.mjs';
import {applyContinuityPlan,continuityFingerprint,missingAnchors,composeLocationSheet} from '../lib/continuity.mjs';
import {referenceLegend} from '../lib/openai-image.mjs';
const PNG='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a3WQAAAAASUVORK5CYII=';
function fixture(){const script='민지는 카페에서 준호를 만났다. 잠시 뒤 같은 카페에서 준호가 웃었다.';const p={id:'project',name:'공간과 인물 연속성',script,constraints:'글자 금지',aspectRatio:'16:9',defaultStyleId:'',characters:[{id:'minji',name:'민지',description:'검은 단발, 노란 우비',references:[]}],locations:[]};p.scenes=validateScenes([{sourceText:'민지는 카페에서 준호를 만났다.',prompt:'wide two shot of Minji and Junho inside one cafe',characterIds:['minji']},{sourceText:'잠시 뒤 같은 카페에서 준호가 웃었다.',prompt:'close up of Junho in the same cafe',characterIds:[]}],script,p.characters);return p;}
const plan=p=>({characters:[{id:'minji',name:'민지',description:'검은 단발, 노란 우비'},{id:'junho',name:'준호',description:'갈색 곱슬머리, 둥근 안경, 파란 셔츠'}],locations:[{id:'cafe',name:'동네 카페',description:'붉은 벽돌벽, 왼쪽 입구, 오른쪽 큰 창문, 중앙 참나무 테이블'}],shots:p.scenes.map((s,i)=>({sceneId:s.id,characterIds:i?['junho']:['minji','junho'],locationIds:['cafe']}))});
test('planner discovers unsheeted characters and fixed locations atomically and reuses canonical IDs/references',()=>{
 const p=fixture(),r=plan(p);applyContinuityPlan(p,r);assert.equal(p.characters.length,2);assert.equal(p.locations.length,1);const junho=p.characters[1],cafe=p.locations[0];assert.equal(p.scenes[1].characterIds[0],junho.id);assert.ok(p.scenes.every(s=>s.locationIds[0]===cafe.id));
 junho.references.push({id:'ref',path:'ref.png'});applyContinuityPlan(p,r);assert.equal(p.characters.length,2);assert.equal(p.locations.length,1);assert.equal(p.characters[1].id,junho.id);assert.equal(p.characters[1].references.length,1);assert.equal(p.continuityPlan.fingerprint,continuityFingerprint(p));
 const before=JSON.stringify(p),bad=plan(p);bad.shots[1].locationIds=['missing'];assert.throws(()=>applyContinuityPlan(p,bad),/알 수 없는/);assert.equal(JSON.stringify(p),before);
 assert.equal(missingAnchors(p,[p.scenes[1]]).length,1);const hash=continuityFingerprint(p);junho.references.push({id:'other'});assert.equal(continuityFingerprint(p),hash);p.script+='!';assert.notEqual(continuityFingerprint(p),hash);
});
test('character and environment references have separate roles and too many references never silently lose a location',()=>{
 const p=fixture();applyContinuityPlan(p,plan(p));for(const [i,c]of p.characters.entries())c.references=[{path:`/char-${i}.png`,kind:'character-sheet'}];p.locations[0].references=[{path:'/cafe.png',kind:'location-sheet'}];const result=composePrompt(p,p.scenes[0],[]);assert.equal(result.refs.length,3);assert.equal(result.refs[2].purpose,'location');assert.match(result.prompt,/furniture positions/);assert.match(referenceLegend(result.refs).legend,/location "동네 카페"/);assert.throws(()=>referenceLegend(Array.from({length:17},(_,i)=>({path:`/${i}`,character:'x'}))),/최대 16장/);
 const sheet=composeLocationSheet(p,p.locations[0],null);assert.match(sheet.prompt,/No people/);assert.match(sheet.prompt,/SAME coherent space/);
});
const waitFor=async(check)=>{for(let i=0;i<160;i++){const value=await check();if(value)return value;await new Promise(r=>setTimeout(r,30));}throw Error('timed out');};
const listen=async s=>{s.listen(0,'127.0.0.1');await once(s,'listening');return s.address().port;};
async function setup(t){
 const dir=await mkdtemp(path.join(tmpdir(),'ssul-continuity-')),data=path.join(dir,'data'),refs=path.join(dir,'refs');await mkdir(data);await mkdir(refs);const p=fixture();const supplied={id:'minji-ref',name:'직접 첨부한 민지.png',kind:'character-sheet',path:'참고이미지/11111111-1111-4111-8111-111111111111.png',url:'/media/references/11111111-1111-4111-8111-111111111111.png'};p.characters[0].references=[supplied];await writeFile(path.join(refs,path.basename(supplied.path)),Buffer.from(PNG,'base64'));
 await writeFile(path.join(data,'state.json'),JSON.stringify({projects:[p],presets:[],sources:[],favorites:[],settings:{codexModel:'gpt-test',imageProvider:'openai'}}));await writeFile(path.join(data,'secrets.json'),JSON.stringify({openaiApiKey:'sk-fixture'}));await writeFile(path.join(dir,'mode'),'success');
 const binary=path.join(dir,'codex');await writeFile(binary,`#!${process.execPath}
const fs=require('node:fs');let input='';process.stdin.on('data',d=>input+=d).on('end',()=>{if(fs.readFileSync(${JSON.stringify(path.join(dir,'mode'))},'utf8')==='hang')return setInterval(()=>{},1000);const p=JSON.parse(input.slice(input.indexOf('{'))),a=process.argv.slice(2);fs.appendFileSync(${JSON.stringify(path.join(dir,'plans'))},'plan\\n');const result=${JSON.stringify(plan(p))};result.shots=p.scenes.map((s,i)=>({sceneId:s.id,characterIds:i?['junho']:['minji','junho'],locationIds:['cafe']}));fs.writeFileSync(a[a.indexOf('-o')+1],JSON.stringify(result));});
`);await chmod(binary,0o755);
 const requests=[];let failure=false,hold=false,active=0,maxActive=0;const releases=[];
 const mock=http.createServer((req,res)=>{let body='';req.on('data',d=>body+=d).on('end',()=>{active++;maxActive=Math.max(maxActive,active);requests.push({url:req.url,body});const done=()=>{active--;res.writeHead(failure?403:200,{'Content-Type':'application/json'});res.end(JSON.stringify(failure?{error:{message:'fixture failure'}}:{data:[{b64_json:PNG}]}));};if(hold)releases.push(done);else setTimeout(done,60);});});const mp=await listen(mock),probe=http.createServer(),port=await listen(probe);await new Promise(r=>probe.close(r));
 const child=spawn(process.execPath,['server.mjs'],{cwd:path.resolve(import.meta.dirname,'..'),env:{...process.env,PORT:String(port),SCENE_DATA_DIR:data,SCENE_REFERENCE_DIR:refs,CODEX_BIN:binary,OPENAI_BASE_URL:`http://127.0.0.1:${mp}/v1`},stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',d=>output+=d);child.stderr.on('data',d=>output+=d);await waitFor(()=>output.includes('Scene Studio:'));t.after(()=>{child.kill();mock.closeAllConnections();mock.close();});
 const api=async(route,body)=>{const r=await fetch(`http://127.0.0.1:${port}/api/${route}`,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};const project=async()=> (await api('state')).body.projects[0];
 return {dir,data,base:`http://127.0.0.1:${port}`,api,project,requests,releases,setFailure:v=>failure=v,setHold:v=>hold=v,maxActive:()=>maxActive};
}
test('generation prepares missing canonical assets before all cuts; reuses uploaded sheets and shares exact anchors on regeneration',async t=>{
 const f=await setup(t);assert.equal((await f.api('projects/project/generate',{})).body.preparing,true);const done=await waitFor(async()=>{const p=await f.project();return p.scenes.every(s=>s.status==='done')&&p;});assert.equal(done.continuityRun.status,'done');assert.equal(done.continuityRun.assets.length,2);assert.equal(f.requests.length,4);assert.ok(f.maxActive()<=3);assert.equal(done.characters[0].references.length,1);assert.equal(done.characters[1].references.length,1);assert.equal(done.locations[0].references.length,1);
 assert.match(f.requests[0].body,/REFERENCE-SHEET TEMPLATE|environment reference sheet/);assert.match(f.requests[1].body,/REFERENCE-SHEET TEMPLATE|environment reference sheet/);for(const call of f.requests.slice(2)){assert.equal(call.url,'/v1/images/edits');assert.match(call.body,/location "동네 카페"/);assert.match(call.body,/character "준호"/);assert.match(call.body,new RegExp(path.basename(done.locations[0].references[0].path)));}
 assert.equal(done.scenes.map(s=>s.sourceText).join(''),done.script);const count=f.requests.length;await f.api('projects/project/generate',{sceneIds:[done.scenes[1].id]});await waitFor(async()=> (await f.project()).scenes[1].images.length===2);assert.equal(f.requests.length,count+1);assert.equal((await readFile(path.join(f.dir,'plans'),'utf8')).trim(),'plan');
 const im=(await f.project()).scenes[1].images[1],sidecar=await (await fetch(f.base+im.metadataUrl)).json();assert.equal(sidecar.cue.locations[0].name,'동네 카페');assert.equal(sidecar.cue.characters[0].name,'준호');
});
test('a failed anchor blocks scene production and retry reuses already completed assets',async t=>{
 const f=await setup(t);f.setFailure(true);await f.api('projects/project/generate',{});const failed=await waitFor(async()=>{const p=await f.project();return p.continuityRun?.status==='failed'&&p;});assert.ok(failed.scenes.every(s=>!s.images.length));assert.equal(f.requests.length,2);assert.match(failed.continuityRun.error,/403/);f.setFailure(false);await f.api('projects/project/generate',{});await waitFor(async()=> (await f.project()).scenes.every(s=>s.status==='done'));assert.equal(f.requests.length,6);assert.equal((await readFile(path.join(f.dir,'plans'),'utf8')).trim(),'plan');
});
test('planning can be cancelled without losing old cuts; a later request can prepare again',async t=>{
 const f=await setup(t);await writeFile(path.join(f.dir,'mode'),'hang');await f.api('projects/project/continuity',{});assert.equal((await f.api('projects/project/continuity',{})).status,400);assert.equal((await f.api('projects/project/continuity-cancel',{})).status,202);const cancelled=await waitFor(async()=>{const p=await f.project();return p.continuityRun?.status==='cancelled'&&p;});assert.equal(cancelled.scenes.length,2);assert.equal(f.requests.length,0);await writeFile(path.join(f.dir,'mode'),'success');await f.api('projects/project/continuity',{});const ready=await waitFor(async()=>{const p=await f.project();return p.continuityRun?.status==='done'&&p;});assert.ok(ready.scenes.every(s=>!s.images.length));assert.equal(f.requests.length,2);
});
test('cancelling in the reference phase stops scene generation, then a fresh request succeeds',async t=>{
 const f=await setup(t);f.setHold(true);await f.api('projects/project/generate',{});await waitFor(()=>f.requests.length===2);assert.equal((await f.api('projects/project/continuity-cancel',{})).status,202);const stopped=await waitFor(async()=>{const p=await f.project();return p.continuityRun?.status==='cancelled'&&p;});assert.ok(stopped.scenes.every(s=>!s.images.length));f.releases.forEach(release=>release());f.setHold(false);await f.api('projects/project/generate',{});await waitFor(async()=> (await f.project()).scenes.every(s=>s.status==='done'));assert.equal((await readFile(path.join(f.dir,'plans'),'utf8')).trim(),'plan');
});
test('location references survive moving the project folder and resolve only selected locations',async()=>{
 const {resolveProjectReferences,migrateReferences}=await import('../lib/references.mjs');const dir=await mkdtemp(path.join(tmpdir(),'ssul-place-portable-')),data=path.join(dir,'data'),refs=path.join(dir,'refs');await mkdir(path.join(data,'references'),{recursive:true});const name='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa.png';await writeFile(path.join(data,'references',name),Buffer.from(PNG,'base64'));const p=fixture();p.locations=[{id:'cafe',name:'카페',description:'붉은 벽',references:[{path:'/old-mac/refs/'+name,name:'카페.png'}]}];const db={projects:[p],presets:[]};assert.equal((await migrateReferences(db,{dataDir:data,referenceDir:refs})).missing.length,0);assert.equal(p.locations[0].references[0].path,'참고이미지/'+name);assert.equal((await resolveProjectReferences(p,refs)).locations[0].references[0].path,path.join(refs,name));assert.deepEqual(await readFile(path.join(refs,name)),Buffer.from(PNG,'base64'));
});
